// SPDX-License-Identifier: Apache-2.0
// Host implementation of chysx::collision::OptixEFBroadphase.

#ifdef _WIN32
#define NOMINMAX
#endif

#include "optix_ef_broadphase.h"

#include <optix.h>
#include <optix_function_table_definition.h>
#include <optix_stubs.h>
#include <optix_stack_size.h>

#include <cuda.h>
#include <cuda_runtime.h>

#include <algorithm>
#include <cstring>
#include <iostream>
#include <stdexcept>
#include <string>

// Embedded PTX from optix_ef_device.cu, generated by bin2c at build time
extern "C" char chysx_optix_ef_ptx[];

// Forward-declared AABB kernel launcher (in optix_ef_kernels.cu)
namespace chysx { namespace collision {
void optix_ef_build_aabbs(float* aabb_buffer, const float3* verts,
                           const int3* tris, float thickness,
                           int n_faces, cudaStream_t stream);
void optix_ef_flatten_hits(const int* hits_buffer,
                           const int* hit_counts,
                           int n_edges,
                           int max_hits_per_edge,
                           math::Vec2i* ef_pairs,
                           int* pair_count,
                           int max_pairs,
                           cudaStream_t stream);
}}

namespace chysx {
namespace collision {

using namespace optix_ef;

namespace {

#define CHYSX_OPTIX_CHECK(call)                                                \
    do {                                                                        \
        OptixResult res = call;                                                 \
        if (res != OPTIX_SUCCESS) {                                             \
            throw std::runtime_error(                                           \
                std::string("OptiX call failed: ") + optixGetErrorName(res) +   \
                " at " + __FILE__ + ":" + std::to_string(__LINE__));            \
        }                                                                       \
    } while (0)

#define CHYSX_CUDA_CHECK(call)                                                 \
    do {                                                                        \
        cudaError_t err = call;                                                 \
        if (err != cudaSuccess) {                                               \
            throw std::runtime_error(                                           \
                std::string("CUDA call failed: ") + cudaGetErrorString(err) +   \
                " at " + __FILE__ + ":" + std::to_string(__LINE__));            \
        }                                                                       \
    } while (0)

void optix_log_cb(unsigned int level, const char* tag, const char* msg, void*) {
    if (level <= 2)
        std::cerr << "[OptiX " << level << "][" << tag << "]: " << msg << "\n";
}

template <typename T>
struct SbtRecord {
    __align__(OPTIX_SBT_RECORD_ALIGNMENT) char header[OPTIX_SBT_RECORD_HEADER_SIZE];
    T data;
};

}  // namespace

// ============================================================================
// Lifecycle
// ============================================================================

OptixEFBroadphase::OptixEFBroadphase() = default;

OptixEFBroadphase::~OptixEFBroadphase() {
    if (pipeline_) optixPipelineDestroy(pipeline_);
    if (raygen_pg_) optixProgramGroupDestroy(raygen_pg_);
    if (miss_pg_) optixProgramGroupDestroy(miss_pg_);
    if (hitgroup_pg_) optixProgramGroupDestroy(hitgroup_pg_);
    if (module_) optixModuleDestroy(module_);
    if (context_) optixDeviceContextDestroy(context_);
    if (gas_output_) cudaFree(reinterpret_cast<void*>(gas_output_));
    if (gas_temp_) cudaFree(reinterpret_cast<void*>(gas_temp_));
    if (gpu_params_) cudaFree(reinterpret_cast<void*>(gpu_params_));
    if (sbt_raygen_) cudaFree(reinterpret_cast<void*>(sbt_raygen_));
    if (sbt_miss_) cudaFree(reinterpret_cast<void*>(sbt_miss_));
    if (sbt_hitgroup_) cudaFree(reinterpret_cast<void*>(sbt_hitgroup_));
}

// ============================================================================
// Setup
// ============================================================================

void OptixEFBroadphase::setup(const std::vector<math::Vec3i>& tris,
                               int n_verts,
                               int max_hits_per_edge) {
    topology_.build(tris, n_verts);
    if (!topology_.valid()) return;

    n_faces_ = topology_.n_faces();
    n_edges_ = topology_.n_edges();
    max_hits_per_edge_ = std::max(1, max_hits_per_edge);
    max_ef_candidates_ = std::max(1, n_edges_ * max_hits_per_edge_);

    // Allocate per-edge output
    hits_buffer_.resize(static_cast<size_t>(n_edges_) * max_hits_per_edge_);
    hit_counts_.resize(n_edges_);
    ef_pairs_.resize(static_cast<size_t>(max_ef_candidates_));
    ef_count_.resize(1);
    ef_count_.cpu_data()[0] = 0;
    ef_count_.copy_to_device();

    // Allocate AABB buffer (6 floats per face)
    aabb_buffer_.resize(static_cast<size_t>(n_faces_) * 6);

    create_context();
    create_pipeline();

    // Allocate GPU launch params
    CHYSX_CUDA_CHECK(cudaMalloc(reinterpret_cast<void**>(&gpu_params_),
                                sizeof(Params)));

    initialized_ = true;
}

void OptixEFBroadphase::create_context() {
    CHYSX_OPTIX_CHECK(optixInit());

    CUcontext cu_ctx = 0;
    OptixDeviceContextOptions opts{};
    opts.logCallbackFunction = &optix_log_cb;
    opts.logCallbackLevel = 2;
    CHYSX_OPTIX_CHECK(optixDeviceContextCreate(cu_ctx, &opts, &context_));
}

void OptixEFBroadphase::create_pipeline() {
    // Module compile options
    OptixModuleCompileOptions module_opts{};
    module_opts.maxRegisterCount = OPTIX_COMPILE_DEFAULT_MAX_REGISTER_COUNT;
    module_opts.optLevel = OPTIX_COMPILE_OPTIMIZATION_DEFAULT;
    module_opts.debugLevel = OPTIX_COMPILE_DEBUG_LEVEL_MINIMAL;

    // Pipeline compile options
    OptixPipelineCompileOptions pipeline_opts{};
    pipeline_opts.usesMotionBlur = false;
    pipeline_opts.traversableGraphFlags = OPTIX_TRAVERSABLE_GRAPH_FLAG_ALLOW_SINGLE_GAS;
    pipeline_opts.numPayloadValues = 1;
    pipeline_opts.numAttributeValues = 3;
    pipeline_opts.exceptionFlags = OPTIX_EXCEPTION_FLAG_NONE;
    pipeline_opts.pipelineLaunchParamsVariableName = "params";
    pipeline_opts.usesPrimitiveTypeFlags = OPTIX_PRIMITIVE_TYPE_FLAGS_CUSTOM;

    // Create module from embedded PTX
    char log_buf[2048];
    size_t log_size = sizeof(log_buf);
    std::string ptx = chysx_optix_ef_ptx;

    CHYSX_OPTIX_CHECK(optixModuleCreate(
        context_, &module_opts, &pipeline_opts,
        ptx.c_str(), ptx.size(),
        log_buf, &log_size, &module_));

    // Program groups
    OptixProgramGroupOptions pg_opts{};

    // Raygen
    {
        OptixProgramGroupDesc desc{};
        desc.kind = OPTIX_PROGRAM_GROUP_KIND_RAYGEN;
        desc.raygen.module = module_;
        desc.raygen.entryFunctionName = "__raygen__ef";
        log_size = sizeof(log_buf);
        CHYSX_OPTIX_CHECK(optixProgramGroupCreate(
            context_, &desc, 1, &pg_opts, log_buf, &log_size, &raygen_pg_));
    }

    // Miss
    {
        OptixProgramGroupDesc desc{};
        desc.kind = OPTIX_PROGRAM_GROUP_KIND_MISS;
        desc.miss.module = module_;
        desc.miss.entryFunctionName = "__miss__ms";
        log_size = sizeof(log_buf);
        CHYSX_OPTIX_CHECK(optixProgramGroupCreate(
            context_, &desc, 1, &pg_opts, log_buf, &log_size, &miss_pg_));
    }

    // Hitgroup (custom intersection + anyhit)
    {
        OptixProgramGroupDesc desc{};
        desc.kind = OPTIX_PROGRAM_GROUP_KIND_HITGROUP;
        desc.hitgroup.moduleIS = module_;
        desc.hitgroup.entryFunctionNameIS = "__intersection__ef";
        desc.hitgroup.moduleAH = module_;
        desc.hitgroup.entryFunctionNameAH = "__anyhit__ef";
        desc.hitgroup.moduleCH = nullptr;
        desc.hitgroup.entryFunctionNameCH = nullptr;
        log_size = sizeof(log_buf);
        CHYSX_OPTIX_CHECK(optixProgramGroupCreate(
            context_, &desc, 1, &pg_opts, log_buf, &log_size, &hitgroup_pg_));
    }

    // Link pipeline
    OptixProgramGroup groups[] = {raygen_pg_, miss_pg_, hitgroup_pg_};
    OptixPipelineLinkOptions link_opts{};
    link_opts.maxTraceDepth = 1;
    log_size = sizeof(log_buf);
    CHYSX_OPTIX_CHECK(optixPipelineCreate(
        context_, &pipeline_opts, &link_opts,
        groups, 3, log_buf, &log_size, &pipeline_));

    // SBT
    using RayGenRecord = SbtRecord<RayGenData>;
    using MissRecord = SbtRecord<MissData>;
    using HitRecord = SbtRecord<HitGroupData>;

    RayGenRecord rg_rec{};
    CHYSX_OPTIX_CHECK(optixSbtRecordPackHeader(raygen_pg_, &rg_rec));
    CHYSX_CUDA_CHECK(cudaMalloc(reinterpret_cast<void**>(&sbt_raygen_), sizeof(RayGenRecord)));
    CHYSX_CUDA_CHECK(cudaMemcpy(reinterpret_cast<void*>(sbt_raygen_), &rg_rec, sizeof(RayGenRecord), cudaMemcpyHostToDevice));

    MissRecord ms_rec{};
    CHYSX_OPTIX_CHECK(optixSbtRecordPackHeader(miss_pg_, &ms_rec));
    CHYSX_CUDA_CHECK(cudaMalloc(reinterpret_cast<void**>(&sbt_miss_), sizeof(MissRecord)));
    CHYSX_CUDA_CHECK(cudaMemcpy(reinterpret_cast<void*>(sbt_miss_), &ms_rec, sizeof(MissRecord), cudaMemcpyHostToDevice));

    HitRecord hg_rec{};
    CHYSX_OPTIX_CHECK(optixSbtRecordPackHeader(hitgroup_pg_, &hg_rec));
    CHYSX_CUDA_CHECK(cudaMalloc(reinterpret_cast<void**>(&sbt_hitgroup_), sizeof(HitRecord)));
    CHYSX_CUDA_CHECK(cudaMemcpy(reinterpret_cast<void*>(sbt_hitgroup_), &hg_rec, sizeof(HitRecord), cudaMemcpyHostToDevice));

    sbt_.raygenRecord = sbt_raygen_;
    sbt_.missRecordBase = sbt_miss_;
    sbt_.missRecordStrideInBytes = sizeof(MissRecord);
    sbt_.missRecordCount = 1;
    sbt_.hitgroupRecordBase = sbt_hitgroup_;
    sbt_.hitgroupRecordStrideInBytes = sizeof(HitRecord);
    sbt_.hitgroupRecordCount = 1;
}

// ============================================================================
// BVH build / refit
// ============================================================================

void OptixEFBroadphase::build_gas(const math::Vec3f* positions_dev,
                                   float thickness,
                                   std::uintptr_t cuda_stream) {
    cudaStream_t stream = reinterpret_cast<cudaStream_t>(cuda_stream);

    // Build AABBs
    optix_ef_build_aabbs(aabb_buffer_.gpu_data(),
                          reinterpret_cast<const float3*>(positions_dev),
                          reinterpret_cast<const int3*>(topology_.faces().gpu_data()),
                          thickness, n_faces_, stream);

    // Configure custom AABB build input
    OptixBuildInput build_input{};
    build_input.type = OPTIX_BUILD_INPUT_TYPE_CUSTOM_PRIMITIVES;
    CUdeviceptr aabb_ptr = reinterpret_cast<CUdeviceptr>(aabb_buffer_.gpu_data());
    build_input.customPrimitiveArray.aabbBuffers = &aabb_ptr;
    build_input.customPrimitiveArray.numPrimitives = static_cast<unsigned int>(n_faces_);
    unsigned int flags = OPTIX_GEOMETRY_FLAG_NONE;
    build_input.customPrimitiveArray.flags = &flags;
    build_input.customPrimitiveArray.numSbtRecords = 1;

    accel_options_ = {};
    accel_options_.buildFlags = OPTIX_BUILD_FLAG_ALLOW_UPDATE | OPTIX_BUILD_FLAG_PREFER_FAST_BUILD;
    accel_options_.operation = OPTIX_BUILD_OPERATION_BUILD;

    OptixAccelBufferSizes buf_sizes{};
    CHYSX_OPTIX_CHECK(optixAccelComputeMemoryUsage(
        context_, &accel_options_, &build_input, 1, &buf_sizes));

    if (gas_temp_size_ < buf_sizes.tempSizeInBytes) {
        if (gas_temp_) cudaFree(reinterpret_cast<void*>(gas_temp_));
        gas_temp_size_ = buf_sizes.tempSizeInBytes;
        CHYSX_CUDA_CHECK(cudaMalloc(reinterpret_cast<void**>(&gas_temp_), gas_temp_size_));
    }
    if (gas_output_size_ < buf_sizes.outputSizeInBytes) {
        if (gas_output_) cudaFree(reinterpret_cast<void*>(gas_output_));
        gas_output_size_ = buf_sizes.outputSizeInBytes;
        CHYSX_CUDA_CHECK(cudaMalloc(reinterpret_cast<void**>(&gas_output_), gas_output_size_));
    }

    CHYSX_OPTIX_CHECK(optixAccelBuild(
        context_, stream, &accel_options_, &build_input, 1,
        gas_temp_, gas_temp_size_,
        gas_output_, gas_output_size_,
        &gas_handle_, nullptr, 0));
}

void OptixEFBroadphase::refit_gas(const math::Vec3f* positions_dev,
                                    float thickness,
                                    std::uintptr_t cuda_stream) {
    cudaStream_t stream = reinterpret_cast<cudaStream_t>(cuda_stream);

    optix_ef_build_aabbs(aabb_buffer_.gpu_data(),
                          reinterpret_cast<const float3*>(positions_dev),
                          reinterpret_cast<const int3*>(topology_.faces().gpu_data()),
                          thickness, n_faces_, stream);

    CUdeviceptr aabb_ptr = reinterpret_cast<CUdeviceptr>(aabb_buffer_.gpu_data());
    OptixBuildInput build_input{};
    build_input.type = OPTIX_BUILD_INPUT_TYPE_CUSTOM_PRIMITIVES;
    build_input.customPrimitiveArray.aabbBuffers = &aabb_ptr;
    build_input.customPrimitiveArray.numPrimitives = static_cast<unsigned int>(n_faces_);
    unsigned int flags = OPTIX_GEOMETRY_FLAG_NONE;
    build_input.customPrimitiveArray.flags = &flags;
    build_input.customPrimitiveArray.numSbtRecords = 1;

    accel_options_.operation = OPTIX_BUILD_OPERATION_UPDATE;

    CHYSX_OPTIX_CHECK(optixAccelBuild(
        context_, stream, &accel_options_, &build_input, 1,
        gas_temp_, gas_temp_size_,
        gas_output_, gas_output_size_,
        &gas_handle_, nullptr, 0));
}

// ============================================================================
// Query
// ============================================================================

void OptixEFBroadphase::query(const math::Vec3f* positions_dev,
                               float thickness,
                               std::uintptr_t cuda_stream) {
    if (!initialized_) return;

    // Build or refit (rebuild every 50 frames for quality)
    if (rebuild_counter_ % 50 == 0)
        build_gas(positions_dev, thickness, cuda_stream);
    else
        refit_gas(positions_dev, thickness, cuda_stream);
    rebuild_counter_++;

    // Update launch params
    cpu_params_.vertices = reinterpret_cast<const float3*>(positions_dev);
    cpu_params_.edges = reinterpret_cast<const int2*>(topology_.edges().gpu_data());
    cpu_params_.triangles = reinterpret_cast<const int3*>(topology_.faces().gpu_data());
    cpu_params_.thickness = thickness;
    cpu_params_.handle = gas_handle_;
    cpu_params_.hits_buffer = hits_buffer_.gpu_data();
    cpu_params_.hit_counts = hit_counts_.gpu_data();
    cpu_params_.max_hits_per_edge = max_hits_per_edge_;

    CHYSX_CUDA_CHECK(cudaMemcpy(
        reinterpret_cast<void*>(gpu_params_), &cpu_params_,
        sizeof(Params), cudaMemcpyHostToDevice));

    cudaStream_t stream = reinterpret_cast<cudaStream_t>(cuda_stream);
    CHYSX_OPTIX_CHECK(optixLaunch(
        pipeline_, stream, gpu_params_, sizeof(Params),
        &sbt_, static_cast<unsigned int>(n_edges_), 1, 1));
    optix_ef_flatten_hits(hits_buffer_.gpu_data(),
                          hit_counts_.gpu_data(),
                          n_edges_,
                          max_hits_per_edge_,
                          ef_pairs_.gpu_data(),
                          ef_count_.gpu_data(),
                          max_ef_candidates_,
                          stream);
}

// ============================================================================
// Download results
// ============================================================================

int OptixEFBroadphase::ef_count(std::uintptr_t cuda_stream) {
    int count = 0;
    cudaStream_t stream = reinterpret_cast<cudaStream_t>(cuda_stream);
    if (stream) cudaStreamSynchronize(stream);
    CHYSX_CUDA_CHECK(cudaMemcpy(&count, ef_count_.gpu_data(), sizeof(int),
                                cudaMemcpyDeviceToHost));
    return std::min(count, max_ef_candidates_);
}

void OptixEFBroadphase::download_pairs(std::vector<math::Vec2i>& out,
                                         std::uintptr_t cuda_stream) {
    if (!initialized_) { out.clear(); return; }

    const int n = ef_count(cuda_stream);
    out.resize(static_cast<std::size_t>(n));
    if (n == 0) return;

    cudaStream_t stream = reinterpret_cast<cudaStream_t>(cuda_stream);
    CHYSX_CUDA_CHECK(cudaMemcpyAsync(out.data(),
                                     ef_pairs_.gpu_data(),
                                     static_cast<std::size_t>(n) *
                                         sizeof(math::Vec2i),
                                     cudaMemcpyDeviceToHost,
                                     stream));
    CHYSX_CUDA_CHECK(cudaStreamSynchronize(stream));
}

}  // namespace collision
}  // namespace chysx
